### ISSUE TITLE
RangeError in JetClient.allMarkets()

### ISSUE THREAD

**Issue by stella3d** [jet-lab/jet-engine#5]
I'm trying to use `jetClient.allMarkets()` to fetch all Market accounts, and always get this range error when it's decoding.

```
RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 8703. Received 8704
    at boundsError (internal/buffer.js:83:9)
    at Buffer.readUInt8 (internal/buffer.js:249:5)
    at Buffer.readUIntLE (internal/buffer.js:179:17)
    at UInt.decode (./node_modules/buffer-layout/lib/Layout.js:570:14)
    at Sequence.decode (./node_modules/buffer-layout/lib/Layout.js:1090:34)
    at Structure.decode (./node_modules/buffer-layout/lib/Layout.js:1234:32)
    at WrappedLayout.decode (./node_modules/@project-serum/borsh/dist/lib/index.js:62:41)
    at Structure.decode (./node_modules/buffer-layout/lib/Layout.js:1234:32)
    at AccountsCoder.decode (./node_modules/@project-serum/anchor/dist/cjs/coder/accounts.js:42:23)
    at ./node_modules/@project-serum/anchor/dist/cjs/program/namespace/account.js:163:47
```

The similar methods `jetClient.allObligations()` & `jetClient.allReserves()` function as expected.

Here's my setup reduced to a minimal TS example: compile with `tsc` and run to reproduce.
```typescript
import { JetClient } from '@jet-lab/jet-engine';
import { Provider, Wallet } from '@project-serum/anchor';
import * as solW3 from '@solana/web3.js';

const rpc = new solW3.Connection('https://api.devnet.solana.com');
const wallet = new Wallet(solW3.Keypair.generate());
const provider = new Provider(rpc, wallet, {});

JetClient.connect(provider, true)
.then(jet => {
    jet.allMarkets()
    .then(markets => { console.log(markets) }, 
          reason => { console.error(reason) });
});
```

I'm using `jet-engine` v0.1.7, running on MacOS & Node v14.x.

**Comment by callensm** [comment]
JET-156

**Comment by callensm** [comment]
interesting, the functions seems to all be working when targeting `mainnet-beta` but for `devnet`, you're right, `allMarkets` is having an issue. We'll take a look at it.

**Comment by callensm** [comment]
@stella3d issue for `devnet` is resolve. update to `0.1.9`. the interface is a little different with some other changes that were made but should be reflected in the updates typedocs.
